baseURL = "https://daiyi.co/notes"
languageCode = "en-us"
title = "lifespeed"
theme = "rocinante"
paginate = 7
summaryLength = 0

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "daiyi"

[params]
  # mainSections = ["post", "photos"]
  # email = "email@example.com"
  favicon = "/icon/favicon.jpg"
  about = """
a highlight reel, sketchbook, comics, mountains
"""

  # [[params.links]]
  #   [[params.links.link]]
  #     name = "About"
  #     href = "https://en.wikipedia.org/wiki/Don_Quixote"
  #     new_tab = true
  #   [[params.links.link]]
  #     name = "Email"
  #     href = "/contact"
  #     smart_email_link = true

  # [[params.links]]
  #   [[params.links.link]]
  #     name = "Goodreads"
  #     href = "https://www.goodreads.com/book/show/3836.Don_Quixote"
  #     new_tab = true
  #   [[params.links.link]]
  #     name = "Gutenberg"
  #     href = "https://www.gutenberg.org/files/996/996-h/996-h.htm"
  #     new_tab = true
  #   [[params.links.link]]
  #     name = "Twitter"
  #     href = "https://twitter.com/search?q=%23twijote%20source%3Atwijote&src=typed_query&f=live"
  #     new_tab = true
  #   [[params.links.link]]
  #     name = "Creator"
  #     href = "https://sidverma.io"
  #     new_tab = true

[imaging.exif]
  disableLatLong = true
  disableDate = true